openapi: "3.0.0"
info:
  version: 3.0.0
  title: Gestão de rotas
servers:
- url: http://working-pmove.planmob.com.br/api/v1/rest
paths:
  /route:
    get:
      summary: Lista todas as rotas
      operationId: listRoute
      tags:
      - Route
      responses:
        '200':
          description: Exemplo de modelo
          content:
            'application/json':
              schema:
                $ref: "#/components/schemas/Route"
            'application/xml':
              schema:
                $ref: "#/components/schemas/Route"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Criar rota
      operationId: createRoute
      tags:
      - Route
      requestBody:
        description: Modelo payload
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Route'
          'application/xml':
            schema:
              $ref: '#/components/schemas/Route'
      responses:
        '200':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Route:
      required:
      - company
      - group
      - qrcode
      - name
      - status
      - dateDue
      - dateInsert
      - userInsert
      - dateUpdate
      - userUpdate
      - sla
      - addressComponent
      properties:
        company:
          type: string
        group:
          type: string
        contract:
          type: string
        planning:
          type: string
        planningChild:
          type: string
        attendant:
          type: array
          items:
            type: string
        related:
          type: array
          items:
            type: string
        relatedAlias:
          type: string
        reference:
          type: string
        description:
          type: string
        qrcode:
          type: string
        name:
          type: string
        status:
          type: string
        order:
          type: number
        vip:
          type: boolean
          default: false
          
        dateDisplacement:
          type: string
          format: date-time
        dateStart:
          type: string
          format: date-time
        dateEnd:
          type: string
          format: date-time
        dateSchedule:
          type: string
          format: date-time
        dateDue:
          type: string
          format: date-time
        dateInsert:
          type: string
          format: date-time
        userInsert:
          type: string
        dateUpdate:
          type: string
          format: date-time
        userUpdate:
          type: string
        sync:
          type: boolean
          default: false

        sla:
          type: array
          items:
            $ref: "#/components/schemas/Sla"
        time:
          type: array
          items:
            $ref: "#/components/schemas/Time"
        product:
          type: array
          items:
            $ref: "#/components/schemas/Product"
        contact:
          type: array
          items:
            $ref: "#/components/schemas/Contact"
        parts:
          type: array
          items:
            $ref: "#/components/schemas/Parts"
        app:
          $ref: "#/components/schemas/App"
        fenceOption:
          $ref: "#/components/schemas/FenceOption"
        addressComponent:
          $ref: "#/components/schemas/AddressComponent"
        schedule:
          $ref: "#/components/schemas/Schedule"
        information:
          type: array
          items:
            $ref: "#/components/schemas/Custom"
    Sla:
      required:
      - text
      - value
      properties:
        text:
          type: string
        value:
          type: number
    Time:
      properties:
        text:
          type: string
        value:
          type: number
    Product:
      properties:
        qrcode:
          type: string
        name:
          type: array
          items:
            type: string
        custom:
          type: array
          items:
            $ref: "#/components/schemas/Custom"
    Contact:
      properties:
        name:
          type: string
        email:
          type: array
          items:
            type: string
        phone:
          type: array
          items:
            type: string
        custom:
          type: array
          items:
            $ref: "#/components/schemas/Custom"
    Custom:
      properties:
        label:
          type: string
        value:
          type: string
        type:
          type: string
    Parts:
      properties:
        qrcode:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        quantity:
          type: number
    App:
      properties:
        displacement:
          type: boolean
          default: false
        send:
          type: boolean
          default: false
        receive:
          type: boolean
          default: false
        packageUnregistered:
          type: boolean
          default: true
        signature:
          $ref: "#/components/schemas/Signature"
    Signature:
      properties:
        enabled:
          type: boolean
          default: false
        requiredFields:
          type: array
          enum:
          - Nome
          - E-mail
          - RG
          - CPF
          - Telefone
          - Matrícula
          - Avaliação
          items:
            type: string
    FenceOption:
      properties:
        minimum:
          type: number
        maximum:
          type: number
    AddressComponent:
      properties:
        address:
          type: string
        complement:
          type: string
        latitude:
          type: string
        longitude:
          type: string
    Schedule:
      properties:
        type:
          type: string
          enum:
          - 'null'
          - PM
          - AM
          - TIME
          default: 'null'
        start:
          type: number
        end:
          type: number
    
    Router:
      properties:
        text:
          type: string
    SurveyAnswer:
      properties:
        text:
          type: string
    Information:
      properties:
        text:
          type: string
    Log:
      properties:
        text:
          type: string
          
    package:
      type: array
      items:
        $ref: "./package.yml"
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: number
          format: int32
        message:
          type: string
